[build]
  command = "pip install -r requirements.txt"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  python_version = "3.9"

[[redirects]]
  from = "/*"
  to = "/api/:splat"
  status = 200
